#cloud-config
# Add groups to the system
# Adds the ubuntu group with members 'root' and 'sys'
# and the empty group hashicorp.
groups:
  - ubuntu: [root,sys]
  - hashicorp

# Add users to the system. Users are added after groups are added.
users:
  - default
  - name: terraform
    gecos: terraform
    shell: /bin/bash
    primary_group: hashicorp
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    # ssh_import_id:
    lock_passwd: false
    ssh_authorized_keys:
      - ${ssh_key}

write_files:
  - path: /tmp/install-docker.sh
    permissions: '0755'
    content: !!binary |
      ${install_docker}

  - path: /tmp/docker-compose.yaml
    permissions: '0755'
    content: !!binary |
      ${docker_compose}

  - path: /tmp/.env
    permissions: '0755'
    content: !!binary |
      ${env_file}

runcmd:
  - ["sudo", "/tmp/install-docker.sh"]
  - ["sudo", "docker-compose", "-f", "/tmp/docker-compose.yaml", "up", "-d"]
